# backend/docker-compose.yml
services:
  backend:
    build:
      context: ..                     # Build context is the project root (mahyancheng-go)
      dockerfile: backend/Dockerfile  # Specify the Dockerfile location
    ports:
      - "8000:8000"   # FastAPI (Uvicorn)
      - "6080:6080"   # noVNC web interface
      - "5901:5901"   # VNC
    environment:
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434
      - BROWSER_AGENT_INTERNAL_MODEL=qwen2.5:7b
      - DISPLAY=:99
    volumes:
      - ./tasks:/app/tasks           # Mount tasks directory for persistence (if needed)
      - ./backend/.env:/app/.env       # Mount local .env (if you have one)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: '2gb'
    restart: unless-stopped
